### ISSUE TITLE
Должно быть List<Car> ... = new ArrayList<>();

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/homeWorkLesson12OldCarsCatalogue#2]
https://github.com/dilyarakhabibullina/homeWorkLesson12OldCarsCatalogue/blob/aef135edf1deda20a60601580d143d2f0dd57ae9/src/main/java/ru/itpark/Main.java#L9

**Comment by coursar** [comment]
Тогда все остальные вызовы будут с Car, а не с Object

**Comment by dilyarakhabibullina** [comment]
Я исправила, работает
